### ISSUE TITLE
Product Details Quantity textbox needs to be clearly defined

### ISSUE THREAD

**Issue by jennymnh** [FEISystems/ca-adpq-prototype#171]
The quantity textbox currently is not clearly defined. We should add a quantity label to the textbox as well as autopopulate it with a value of "1".

**Comment by neelusingh28** [comment]
Changes are still NOT reflecting on 5000 site.

**Comment by neelusingh28** [comment]
QTY label is there but it is not auto populating with the value of '1'

**Comment by JXPrime** [comment]
I think this got fixed by https://github.com/FEISystems/ca-adpq-prototype/commit/1a42c20bd3c87bb9d9bf2c7d94225c7e5623589e - @neelusingh28 can you verify?

**Comment by neelusingh28** [comment]
Value '1' is still not auto populating, system displays '1' only when user scroll either top or down.

**Comment by JXPrime** [comment]
I think this will be fixed by #175 when it is ready.

**Comment by neelusingh28** [comment]
Verified and Passed in 5000 site and working as expected in Chrome, Firefox, IE and devices.

**Comment by neelusingh28** [comment]
Value '1' is auto populating in Chrome, Firefox, IE and devices 
BUT
here are NO scroll arrow keys inside the text box in **IE and in devices.**

**Comment by jennymnh** [comment]
This is normal browser behavior and how IE handles HTML 5 inputs. IE does not add the arrows, but Chrome and other browsers may have them. I would say this is not a bug.

Also, what types of devices are you using? On my iPhone's Safari browser when I touch the input I am given  an option to enter numbers, but no arrows either. This is normal. Screenshot below:
![image](https://cloud.githubusercontent.com/assets/9370407/23514802/66b73b06-ff36-11e6-8dbe-0eacecb3d20d.png)

**Comment by neelusingh28** [comment]
All right then this can be closed. Thanks.
