### ISSUE TITLE
Add to cart from product details not working

### ISSUE THREAD

**Issue by llin-freeman** [FEISystems/ca-adpq-prototype#175]
Adding item from product detail page does not update cart.

**Comment by llin-freeman** [comment]
![product page](https://cloud.githubusercontent.com/assets/22507715/23435284/2ca3d42c-fdd5-11e6-8e82-0adf2bdd94fa.png)

**Comment by JXPrime** [comment]
if you're not logged in you'll also have problems adding stuff to your cart, but there was a javascript error on this page that I think is resolved. cc: @llin-freeman

**Comment by neelusingh28** [comment]
Verified and Passed in 5000 site.

**Comment by llin-freeman** [comment]
Thanks! I tried it on the survey site, and it still doesn't work. If you're viewing the product details, and then click add, the item doesn't make it to shopping cart.

**Comment by llin-freeman** [comment]
![added core laptop](https://cloud.githubusercontent.com/assets/22507715/23442595/7f527008-fdf7-11e6-8524-7c7febca88f6.JPG)

**Comment by llin-freeman** [comment]
Clicked "add to cart" from this page, and the cart did not update.

**Comment by jennymnh** [comment]
This has been fixed. Sorry, I broke it when I was adding quantities. :(

**Comment by llin-freeman** [comment]
Thanks, Jenny! I checked on 5000 and on the survey link, and still can't add the item from the product details page.

**Comment by JXPrime** [comment]
@jennymnh looks like the quantity is null being passed to the server which it doesn't like.

**Comment by neelusingh28** [comment]
Adding item from product detail page is still NOT working.

**Comment by JXPrime** [comment]
@neelusingh28 were you logged in? I was able to add an item to the cart from the product detail page on the :5000 site.

**Comment by neelusingh28** [comment]
@JXPrime  - yes, I am making sure that I'm always logged in before performing any action. 5000 site is highly unstable as well as sporadic and particularly cart and compare list :(

I tried again  just now. logged in as AuthorizedUser3 but I'm still not able to add the item to the cart.

![image](https://cloud.githubusercontent.com/assets/25771656/23476634/65e7ba14-fe89-11e6-9446-7bf1f002f2df.png)

**Comment by JXPrime** [comment]
I've found an interesting heisenbug on the :5000 site (I can't reproduce this locally). If you're on the homepage and click on a product to view the details page, you'll get a js error: 
![image](https://cloud.githubusercontent.com/assets/1841009/23477520/70ed2a92-fe7b-11e6-803c-dbff50c2ca63.png)

Once that happens, all the js functionality in that component is broken, so add to cart does nothing.


If you refresh the page, you don't get that error, and add to cart works fine. I'm a bit out of my depth on the angularJS side, I can't even see how a "product" object is getting in to $scope in the first place. Thoughts @lutech @lnajera ?

**Comment by neelusingh28** [comment]
Adding item from product detail page updating cart in Chrome, Firefox and devices but NOT IE

**Comment by JXPrime** [comment]
can't reproduce on the :5000 site. Item went into cart just fine.

**Comment by ClaireReinken** [comment]
Did you try IE?

Claire Reinken, AM.PMP
Senior Proposal Manager

office   | 443.472.4613
fax       | 410.715.6538
email   |  claire.reinken@FEIsystems.com<mailto:claire.reinken@FEIsystems.com>
FEi Systems
9755 Patuxent Woods Drive, Suite 300 Columbia, MD 21046 |  www.FEIsystems.com<http://www.feisystems.com/>

**Comment by JXPrime** [comment]
I can't reproduce this on the 5000 site. If it happens again please have your dev tools open to capture any javascript errors that might be occurring.

**Comment by neelusingh28** [comment]
Closing this issue and opening separate issue for all IE related problems.
