### ISSUE TITLE
Mobile UI Issues

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#195]
The top navigation bar is not responsive and the full home page doesn't show. Picture is cut off.

**Comment by jennymnh** [comment]
The slideshow image is very large and not user friendly for mobile. Can we just hide it?

**Comment by ClaireReinken** [comment]
Fine with me

**Comment by jennymnh** [comment]
Done

**Comment by neelusingh28** [comment]
@jennymnh & @ClaireReinken  Images are hidden from 5000 site but still showing on azure site? I think it should be hidden there too for devices?

**Comment by neelusingh28** [comment]
@jennymnh The slideshow image is till displaying on iPad device. Rest all devices are NOT displaying it for both 5000 site and azure

**Comment by jennymnh** [comment]
I only took it off on small devices (414px wide and less to be exact). I think this should be ok on an iPad, the screen is large enough that the image would not take up most of the screen.

**Comment by neelusingh28** [comment]
all right closing.
